# Copy this to .streamlit/secrets.toml for local development
# For Streamlit Cloud deployment, add these secrets in the app settings

# Required API Key for AI analysis
PERPLEXITY_API_KEY = "your_perplexity_api_key_here"

# Optional: Database configuration (uses local SQLite by default)
# DATABASE_URL = "your_database_url_here"

# Instructions:
# 1. Get your Perplexity API key from: https://www.perplexity.ai/
# 2. For Streamlit Cloud: Go to app settings -> Secrets -> Add the key
# 3. For local development: Create .streamlit/secrets.toml with this content
